using System.Collections.Generic;
using UnityEngine;

namespace AIHWSim.Pack
{
    /// <summary>
    /// The arena kit's palette — the one material table in the pack with no
    /// runtime source to copy from.
    ///
    /// Every other pack material is generated by cloning the material the game
    /// already builds (see <see cref="PackMaterialGenerator"/>), because the game
    /// owns those props. The arena tiles are pack-only by design, so nothing in
    /// <c>Assets/Scripts</c> describes them and these numbers come straight from
    /// <c>build_map_props.py</c>'s MATJSON blocks — measured off the authored
    /// Principled nodes, never eyeballed. Regenerate with
    /// <c>scratchpad/gen_socdata.py</c> rather than editing by hand.
    ///
    /// The kit is a THEME AXIS: all three themes answer the same twenty slot
    /// names, which is exactly why the geometry ships once and only the palette
    /// varies. <see cref="Tokens"/> sorts longest-token-first automatically, the
    /// same defence <c>CosmeticCatalog</c> uses — <c>AssignByName</c> is a
    /// first-match substring matcher, so a hand-ordered table is a latent
    /// wrong-colour bug (<c>glow_a</c> would be swallowed by a bare <c>glow</c>,
    /// <c>team_blue</c> by <c>team</c>).
    ///
    /// Emission is the one adjusted value. The authored ratios are Cycles-scale
    /// (2.3x to 42x their own albedo); Unity's gamma LDR pipeline clips anything
    /// past 1, so these run at roughly half the authored ratio with a ceiling,
    /// and each carries its authored number in a trailing comment.
    /// </summary>
    public static class PackSocData
    {
        public struct MatDef
        {
            public string token;
            public Color baseColor;
            public float metallic;
            public float roughness;
            public float alpha;
            /// <summary>Multiple of its own albedo the surface emits; 0 = unlit.</summary>
            public float glow;
        }

        private static MatDef D(string token, float r, float g, float b,
                                float metallic, float roughness,
                                float alpha, float glow) =>
            new MatDef
            {
                token = token,
                baseColor = new Color(r, g, b, alpha),
                metallic = metallic,
                roughness = roughness,
                alpha = alpha,
                glow = glow,
            };

        /// <summary>The Circuit palette, twenty slots.</summary>
        private static readonly MatDef[] Circuit =
        {
            D("ball", 0.5627f, 0.5737f, 0.5941f, 0.000f, 0.340f, 1.0000f, 0.000f),
            D("banner", 0.3734f, 0.6689f, 0.7766f, 0.000f, 0.420f, 1.0000f, 0.138f),  // authored 0.275x
            D("ceiling", 0.1692f, 0.1767f, 0.2029f, 0.000f, 0.653f, 1.0000f, 0.000f),
            D("cove", 0.2006f, 0.2130f, 0.2528f, 0.000f, 0.447f, 1.0000f, 0.000f),
            D("crowd", 0.2898f, 0.3015f, 0.3389f, 0.000f, 0.780f, 1.0000f, 0.000f),
            D("floor", 0.1863f, 0.2006f, 0.2375f, 0.000f, 0.420f, 1.0000f, 0.000f),
            D("glass", 0.6343f, 0.7484f, 0.8434f, 0.000f, 0.045f, 0.1600f, 0.000f),
            D("glow_a", 0.2478f, 0.4845f, 0.5838f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 30.8x
            D("glow_b", 0.5838f, 0.3492f, 0.1517f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 37.2x
            D("light", 0.7977f, 0.7977f, 0.7977f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 14x
            D("line", 0.8095f, 0.8323f, 0.8650f, 0.000f, 0.300f, 1.0000f, 0.155f),  // authored 0.311x
            D("metal", 0.4492f, 0.4590f, 0.4800f, 1.000f, 0.340f, 1.0000f, 0.000f),
            D("net", 0.2528f, 0.2671f, 0.2934f, 0.000f, 0.720f, 1.0000f, 0.000f),
            D("screen", 0.4366f, 0.5469f, 0.6500f, 0.000f, 0.240f, 1.0000f, 1.296f),  // authored 2.59x
            D("seat", 0.2601f, 0.3035f, 0.3734f, 0.000f, 0.620f, 1.0000f, 0.000f),
            D("sub", 0.1897f, 0.1964f, 0.2151f, 0.000f, 0.700f, 1.0000f, 0.000f),
            D("team_blue", 0.2209f, 0.3811f, 0.6343f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 21.1x
            D("team_orange", 0.6180f, 0.3811f, 0.1517f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 21.4x
            D("trim", 0.3734f, 0.3841f, 0.4100f, 0.550f, 0.300f, 1.0000f, 0.000f),
            D("wall", 0.2340f, 0.2435f, 0.2762f, 0.000f, 0.540f, 1.0000f, 0.000f),
        };

        /// <summary>The Sandlot palette, twenty slots.</summary>
        private static readonly MatDef[] Sandlot =
        {
            D("ball", 0.6097f, 0.6111f, 0.6041f, 0.000f, 0.420f, 1.0000f, 0.000f),
            D("banner", 0.7918f, 0.6836f, 0.6343f, 0.000f, 0.420f, 1.0000f, 0.000f),
            D("ceiling", 0.7220f, 0.7430f, 0.7643f, 0.000f, 0.500f, 1.0000f, 0.000f),
            D("cove", 0.2540f, 0.4067f, 0.2318f, 0.000f, 0.760f, 1.0000f, 0.000f),
            D("crowd", 0.6343f, 0.6012f, 0.5500f, 0.000f, 0.760f, 1.0000f, 0.000f),
            D("floor", 0.2671f, 0.4272f, 0.2409f, 0.000f, 0.740f, 1.0000f, 0.000f),
            D("glass", 0.8650f, 0.9063f, 0.9357f, 0.000f, 0.030f, 0.1000f, 0.000f),
            D("glow_a", 0.6800f, 0.6180f, 0.3492f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 31.1x
            D("glow_b", 0.6500f, 0.4100f, 0.2717f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 41.9x
            D("light", 0.9063f, 0.9063f, 0.9063f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 15.8x
            D("line", 0.9453f, 0.9500f, 0.9453f, 0.000f, 0.440f, 1.0000f, 0.000f),
            D("metal", 0.7484f, 0.7548f, 0.7643f, 1.000f, 0.300f, 1.0000f, 0.000f),
            D("net", 0.8210f, 0.8267f, 0.8210f, 0.000f, 0.660f, 1.0000f, 0.000f),
            D("screen", 0.6944f, 0.7220f, 0.7484f, 0.000f, 0.240f, 1.0000f, 1.158f),  // authored 2.32x
            D("seat", 0.7220f, 0.4492f, 0.3318f, 0.000f, 0.560f, 1.0000f, 0.000f),
            D("sub", 0.4169f, 0.3959f, 0.3624f, 0.000f, 0.720f, 1.0000f, 0.000f),
            D("team_blue", 0.3133f, 0.4614f, 0.6944f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 8.34x
            D("team_orange", 0.6944f, 0.4614f, 0.1897f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 9.72x
            D("trim", 0.7484f, 0.6343f, 0.4731f, 0.000f, 0.480f, 1.0000f, 0.000f),
            D("wall", 0.4956f, 0.4091f, 0.3075f, 0.000f, 0.720f, 1.0000f, 0.000f),
        };

        /// <summary>The Forge palette, twenty slots.</summary>
        private static readonly MatDef[] Forge =
        {
            D("ball", 0.4751f, 0.4665f, 0.4569f, 0.000f, 0.300f, 1.0000f, 0.000f),
            D("banner", 0.7797f, 0.5611f, 0.3227f, 0.000f, 0.420f, 1.0000f, 0.113f),  // authored 0.225x
            D("ceiling", 0.2641f, 0.2427f, 0.2257f, 0.400f, 0.747f, 1.0000f, 0.000f),
            D("cove", 0.4044f, 0.3009f, 0.2112f, 0.550f, 0.700f, 1.0000f, 0.000f),
            D("crowd", 0.3959f, 0.3504f, 0.3100f, 0.000f, 0.780f, 1.0000f, 0.000f),
            D("floor", 0.3152f, 0.2948f, 0.2777f, 0.000f, 0.720f, 1.0000f, 0.000f),
            D("glass", 0.8650f, 0.6944f, 0.4845f, 0.000f, 0.075f, 0.2000f, 0.000f),
            D("glow_a", 0.6343f, 0.3811f, 0.1517f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 30.4x
            D("glow_b", 0.3492f, 0.5469f, 0.6180f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 29.3x
            D("light", 0.7674f, 0.7220f, 0.6652f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 14.1x
            D("line", 0.8756f, 0.8677f, 0.8489f, 0.000f, 0.440f, 1.0000f, 0.201f),  // authored 0.401x
            D("metal", 0.5169f, 0.4845f, 0.4553f, 1.000f, 0.460f, 1.0000f, 0.000f),
            D("net", 0.3734f, 0.3492f, 0.3282f, 0.000f, 0.700f, 1.0000f, 0.000f),
            D("screen", 0.6180f, 0.5271f, 0.4366f, 0.000f, 0.240f, 1.0000f, 1.302f),  // authored 2.6x
            D("seat", 0.4366f, 0.3318f, 0.2348f, 0.000f, 0.600f, 1.0000f, 0.000f),
            D("sub", 0.2762f, 0.2528f, 0.2348f, 0.000f, 0.760f, 1.0000f, 0.000f),
            D("team_blue", 0.2717f, 0.4366f, 0.6652f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 22.2x
            D("team_orange", 0.6652f, 0.3959f, 0.1517f, 0.000f, 0.240f, 1.0000f, 4.000f),  // authored 20.7x
            D("trim", 0.4614f, 0.4236f, 0.3811f, 0.800f, 0.440f, 1.0000f, 0.000f),
            D("wall", 0.3811f, 0.2821f, 0.1987f, 0.700f, 0.673f, 1.0000f, 0.000f),
        };

        /// <summary>Theme names, in the order the authoring module declares them.
        /// These are the folder names under <c>Materials/Arena/</c> and the suffix
        /// on every arena prefab.</summary>
        public static readonly string[] Themes = { "Circuit", "Sandlot", "Forge" };

        public const string DefaultTheme = "Sandlot";

        private static MatDef[] Defs(string theme)
        {
            switch (theme)
            {
                case "Circuit": return Circuit;
                case "Forge": return Forge;
                default: return Sandlot;
            }
        }

        private static readonly Dictionary<string, (string, Material)[]> _tokens =
            new Dictionary<string, (string, Material)[]>();

        /// <summary>Token → material for one theme, longest token first.</summary>
        public static (string, Material)[] Tokens(string theme)
        {
            if (_tokens.TryGetValue(theme, out var cached) && cached != null &&
                cached.Length > 0 && cached[0].Item2 != null)
                return cached;

            var list = new List<(string, Material)>();
            foreach (var d in Defs(theme)) list.Add((d.token, Build(d, theme)));
            // Longest first, by construction rather than by hand — see the class doc.
            list.Sort((a, b) => b.Item1.Length.CompareTo(a.Item1.Length));
            var arr = list.ToArray();
            _tokens[theme] = arr;
            return arr;
        }

        private static Material Build(MatDef d, string theme)
        {
            var m = AIHWSim.Track.TrackBuilder.StandardMat(d.baseColor);
            m.name = "Soc_" + theme + "_" + d.token;
            m.SetFloat("_Metallic", d.metallic);
            // Roughness and smoothness are complements — the exporter prints
            // roughness, Unity Standard wants _Glossiness.
            m.SetFloat("_Glossiness", Mathf.Clamp01(1f - d.roughness));
            if (d.glow > 0f)
            {
                m.EnableKeyword("_EMISSION");
                m.globalIlluminationFlags = MaterialGlobalIlluminationFlags.EmissiveIsBlack;
                m.SetColor("_EmissionColor", new Color(d.baseColor.r * d.glow,
                                                       d.baseColor.g * d.glow,
                                                       d.baseColor.b * d.glow));
            }
            if (d.alpha < 1f) MakeFade(m);
            return m;
        }

        /// <summary>The render-state flags Unity's own StandardShaderGUI writes for
        /// Fade mode. Mirrors CosmeticCatalog's helper, which is private to it.</summary>
        private static void MakeFade(Material m)
        {
            m.SetFloat("_Mode", 2f);
            m.SetInt("_SrcBlend", (int)UnityEngine.Rendering.BlendMode.SrcAlpha);
            m.SetInt("_DstBlend", (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
            m.SetInt("_ZWrite", 0);
            m.DisableKeyword("_ALPHATEST_ON");
            m.EnableKeyword("_ALPHABLEND_ON");
            m.DisableKeyword("_ALPHAPREMULTIPLY_ON");
            m.renderQueue = (int)UnityEngine.Rendering.RenderQueue.Transparent;
        }
    }
}
