using System.Collections.Generic;
using UnityEngine;

namespace AIHWSim.Pack
{
    /// <summary>
    /// One brush: a weighted palette of prefabs plus how to scatter them.
    ///
    /// An editor-only asset — it lives under the pack's <c>Editor/</c> tree, is
    /// never referenced by a scene in Build Settings, and so never reaches a
    /// player build. Presets ship in <c>TinyTorqueAssets/Brushes/</c> and are
    /// regenerated by <see cref="PackBrushMenu"/>, but nothing stops you from
    /// making your own with Create &gt; TinyTorque &gt; Scatter Preset.
    /// </summary>
    [CreateAssetMenu(menuName = "TinyTorque/Scatter Preset", fileName = "ScatterPreset")]
    public sealed class ScatterPreset : ScriptableObject
    {
        [System.Serializable]
        public struct Entry
        {
            public GameObject prefab;
            [Min(0f)] public float weight;
        }

        [Tooltip("What this brush paints. Weights are relative; 0 disables an entry.")]
        public List<Entry> entries = new List<Entry>();

        [Header("Brush")]
        [Tooltip("Radius of the brush disc, in game metres (this world is 1:10 scale, " +
                 "so 1 m is a big brush).")]
        [Min(0.01f)] public float radius = 1.0f;

        [Tooltip("Stamps attempted per drag step. Each one still has to find a surface " +
                 "and clear the avoid radius, so the count placed is usually lower.")]
        [Min(1)] public int density = 3;

        [Header("Variation")]
        public bool randomYaw = true;
        [Min(0f)] public float scaleMin = 0.9f;
        [Min(0f)] public float scaleMax = 1.15f;

        [Tooltip("Tilt each stamp onto the surface normal. Right for rocks and " +
                 "debris; wrong for anything that should stand upright on a slope.")]
        public bool alignToSurface = false;

        [Tooltip("Reject a stamp landing this close to one already placed by this " +
                 "brush. 0 allows overlaps.")]
        [Min(0f)] public float avoidRadius = 0.12f;

        [Header("Surface")]
        [Tooltip("Which layers count as ground. Stamps raycast straight down and are " +
                 "discarded if they hit nothing.")]
        public LayerMask surfaceMask = ~0;

        [Tooltip("Scene object the stamps are parented under, so a pass can be " +
                 "deleted or moved as one thing.")]
        public string parentName = "Scatter";

        /// <summary>Pick a prefab by weight. Returns null if the palette is empty
        /// or every weight is zero, which the brush treats as "nothing to paint"
        /// rather than an error.</summary>
        public GameObject Pick(System.Random rng)
        {
            float total = 0f;
            foreach (var e in entries)
                if (e.prefab != null && e.weight > 0f) total += e.weight;
            if (total <= 0f) return null;

            float r = (float)rng.NextDouble() * total;
            foreach (var e in entries)
            {
                if (e.prefab == null || e.weight <= 0f) continue;
                r -= e.weight;
                if (r <= 0f) return e.prefab;
            }
            foreach (var e in entries)
                if (e.prefab != null && e.weight > 0f) return e.prefab;
            return null;
        }
    }
}
