/* =====================================================================
   tt-jgraph.js — hand a figure over to JGraph.

   JGraph runs one script per process and has no socket or pipe to talk to,
   so the handover is file-based: we write a CSV of the data plus a script
   that plots it, and JGraph is pointed at the script:

       jgraph -batch "<name>.m" -showfigures -sd "<folder>"

   Two deliberate choices:

   • Scripts are generated in MATLAB dialect, not JGS. JGS's `let` requirement
     and its index base are per-user settings that JGraph honours even in
     batch mode, so a generated JGS script could run differently on two
     machines. MATLAB dialect has fixed rules.

   • The data goes out as CSV rather than being inlined in the script. It
     keeps the script readable, and it means the numbers are useful on their
     own — you can open the same CSV in anything.
   ===================================================================== */
(function (global) {
    'use strict';

    /* Build the {csv, script} pair for one figure.
       series: [{name, data:[]}] all sharing the same x vector. */
    function figure(id, title, x, series, opts) {
        const o = opts || {};
        const X = global.TT.Export;
        const name = String(id).replace(/[^A-Za-z0-9_]+/g, '_');

        const cols = ['x'].concat(series.map(function (s) {
            return String(s.name).replace(/[^A-Za-z0-9_]+/g, '_');
        }));
        const csv = X.toCsv(cols, [x].concat(series.map(function (s) { return s.data; })));

        // readcsv gives a table; column(t, n) pulls one column out by name.
        const plots = series.map(function (s, i) {
            const col = cols[i + 1];
            return "    plot(x, column(t, '" + col + "'), '" + strokeFor(i) + "');\n    hold on;";
        }).join('\n');
        const legend = series.map(function (s) { return "'" + s.name.replace(/'/g, '') + "'"; }).join(', ');

        const script =
`% ${title}
% Generated by the Tiny Torque Control Lab.
%
% Run it with:
%     jgraph -batch "${name}.m" -showfigures -sd "<this folder>"
%
% MATLAB dialect is used deliberately: JGS's index base and 'let' requirement
% come from per-user settings, so a generated JGS script could behave
% differently on another machine. This one cannot.

t = readcsv('${name}.csv');
x = column(t, 'x');

figure;
${plots}
title('${title.replace(/'/g, '')}');
xlabel('${(o.xLabel || 'x').replace(/'/g, '')}');
ylabel('${(o.yLabel || 'y').replace(/'/g, '')}');
legend(${legend});
grid(true);
show();
`;
        return {
            id: name,
            files: [
                { name: name + '.csv', text: csv, mime: 'text/csv' },
                { name: name + '.m', text: script, mime: 'text/plain' }
            ],
            command: 'jgraph -batch "' + name + '.m" -showfigures'
        };
    }

    function strokeFor(i) {
        const styles = ['b-', 'r-', 'g-', 'm-', 'c-', 'k--', 'b--', 'r--'];
        return styles[i % styles.length];
    }

    /* Write the pair out. Prefers the remembered jgraph-out folder so the
       bridge script can pick it up; falls back to downloads. */
    function send(fig, statusEl) {
        const X = global.TT.Export;
        const say = function (html) { if (statusEl) statusEl.innerHTML = html; };

        if (!X.supported) {
            X.downloadAll(fig.files);
            say('<span class="ok">Downloaded ' + fig.id + '.m and .csv.</span> This browser has no ' +
                'directory access, so the bridge cannot be used — put both in one folder and run ' +
                '<code>' + fig.command + ' -sd "&lt;that folder&gt;"</code>. ' +
                'Chrome or Edge can write straight into the watched folder instead.');
            return Promise.resolve();
        }
        return X.savedDirectory('jgraph').then(function (found) {
            if (found && found.needsPermission) {
                return X.requestPermission(found.handle).then(function (ok) {
                    return ok ? found.handle : X.pickDirectory('jgraph');
                });
            }
            return found || X.pickDirectory('jgraph');
        }).then(function (dir) {
            return X.writeFiles(dir, fig.files).then(function () { return dir; });
        }).then(function (dir) {
            const where = dir.name || 'the chosen folder';
            let msg = '<span class="ok">Wrote ' + fig.id + '.m and .csv to ' + where + '.</span> ';
            // The page cannot see whether the watcher is alive, but it can see
            // whether the files went somewhere the watcher looks. A wrong folder
            // is the quiet failure — the write succeeds and nothing ever opens.
            if (dir.name && dir.name.toLowerCase() !== 'jgraph-out') {
                msg += '<span class="warn">The bridge watches <code>Tools\\jgraph-out</code>, not ' + where +
                    ', so it will not pick this up.</span> Re-pick that folder, or run <code>' +
                    fig.command + '</code> here yourself.';
            } else {
                msg += 'It opens by itself if the bridge is running — start it with ' +
                    '<code>powershell -ExecutionPolicy Bypass -File Tools\\jgraph-bridge.ps1</code>. ' +
                    'Otherwise run <code>' + fig.command + '</code> there.';
            }
            say(msg);
        }).catch(function (e) {
            if (e && e.name === 'AbortError') { say('Cancelled.'); return; }
            // Falling back to a download is better than failing outright.
            X.downloadAll(fig.files);
            say('<span class="warn">Could not write to a folder (' + (e.message || e) + '), so both files were downloaded instead.</span>');
        });
    }

    /* A button plus its own status line, ready to drop into a panel.
       `build` is called on click so the exported figure is always current. */
    function button(id, build, label) {
        const el = global.TT.UI.el;
        const status = el('span', { class: 'status tiny' });
        const btn = el('button', { class: 'small ghost', text: label || 'Open in JGraph' });
        btn.addEventListener('click', function () {
            const fig = build();
            status.textContent = 'Writing…';
            send(fig, status);
        });
        const wrap = el('span', { style: 'display:inline-flex;gap:8px;align-items:center' }, [btn, status]);
        return wrap;
    }

    global.TT = global.TT || {};
    global.TT.JGraph = { figure: figure, send: send, button: button };
})(typeof window !== 'undefined' ? window : globalThis);
