#!/usr/bin/env node
/*
 * gen_params.js — firmware parameter JSON -> C (FW-07).
 *
 *   node Tools/gen_params.js            regenerate every Controllers/params/*.json
 *   node Tools/gen_params.js --check    exit 1 if any generated file is stale (CI)
 *
 * Each Controllers/params/<name>.json becomes Controllers/core/params_<name>.c,
 * defining `const TtParams tt_params_<name>`. The FIELDS list below must match
 * the TtParams struct in Controllers/core/tt_params.h field for field; the
 * generated file is committed, so building firmware never needs Node.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PARAMS_DIR = path.join(ROOT, 'Controllers', 'params');
const OUT_DIR = path.join(ROOT, 'Controllers', 'core');

// [field, kind]: f = float, u = uint32, f4 = float[4], mask = wheel list -> uint32
const FIELDS = [
    ['version', 'u'],
    ['wheel_radius_m', 'f'], ['wheelbase_m', 'f'], ['track_front_m', 'f'],
    ['mass_kg', 'f'], ['mass_eff_kg', 'f'],
    ['odo_wheel_mask', 'mask'], ['enc_cpr', 'f4'], ['enc_ratio', 'f4'],
    ['driven_mask', 'mask'], ['gear', 'f4'], ['kt', 'f4'],
    ['eta_drive', 'f'], ['eta_back', 'f'],
    ['regen_n_per_ms', 'f'], ['regen_max_n', 'f'], ['regen_grip_cap_n', 'f'],
    ['traction_eff', 'f'], ['v_rail_nom', 'f'],
    ['max_steer_rad', 'f'], ['servo_slew_rad_s', 'f'], ['brake_max_nm', 'f'],
    ['drag_c0', 'f'], ['drag_c1', 'f'], ['drag_c2', 'f'],
    ['cal_scale', 'f'], ['cal_brake', 'f'],
    ['odo_lead_comp', 'u'],
];
const WHEELS = { FL: 0, FR: 1, RL: 2, RR: 3 };

function cFloat(v, where) {
    if (typeof v !== 'number' || !isFinite(v)) throw new Error(`${where}: not a finite number`);
    let s = String(v);
    if (!/[.eE]/.test(s)) s += '.0';
    return s + 'f';
}

function cValue(kind, v, where) {
    switch (kind) {
    case 'f': return cFloat(v, where);
    case 'u':
        if (!Number.isInteger(v) || v < 0) throw new Error(`${where}: not a non-negative integer`);
        return v + 'u';
    case 'f4':
        if (!Array.isArray(v) || v.length !== 4) throw new Error(`${where}: needs 4 values (FL, FR, RL, RR)`);
        return '{ ' + v.map((x, i) => cFloat(x, `${where}[${i}]`)).join(', ') + ' }';
    case 'mask': {
        if (!Array.isArray(v)) throw new Error(`${where}: needs a list of wheels`);
        let m = 0;
        for (const w of v) {
            if (!(w in WHEELS)) throw new Error(`${where}: unknown wheel '${w}'`);
            m |= 1 << WHEELS[w];
        }
        return '0x' + m.toString(16).toUpperCase() + 'u /* ' + v.join(' | ') + ' */';
    }
    }
    throw new Error('bad kind ' + kind);
}

function generate(jsonPath) {
    const src = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    const name = src.name;
    if (!/^[a-z0-9_]+$/.test(name || '')) throw new Error(`${jsonPath}: "name" must be lower_snake`);
    const known = new Set(FIELDS.map(f => f[0]).concat(['name']));
    for (const k of Object.keys(src))
        if (!k.startsWith('_') && !known.has(k)) throw new Error(`${jsonPath}: unknown key '${k}'`);

    const lines = FIELDS.map(([f, kind]) => {
        if (!(f in src)) throw new Error(`${jsonPath}: missing '${f}'`);
        return `    .${f} = ${cValue(kind, src[f], f)},`;
    });
    const rel = path.relative(ROOT, jsonPath).split(path.sep).join('/');
    return [
        `/* GENERATED by Tools/gen_params.js from ${rel} — do not edit. */`,
        '#include "tt_params.h"',
        '',
        `const TtParams tt_params_${name} = {`,
        ...lines,
        '};',
        '',
    ].join('\n');
}

function main() {
    const check = process.argv.includes('--check');
    const files = fs.readdirSync(PARAMS_DIR).filter(f => f.endsWith('.json')).sort();
    let stale = 0;
    for (const f of files) {
        const jsonPath = path.join(PARAMS_DIR, f);
        const out = path.join(OUT_DIR, 'params_' + path.basename(f, '.json') + '.c');
        const text = generate(jsonPath);
        const old = fs.existsSync(out) ? fs.readFileSync(out, 'utf8').replace(/\r\n/g, '\n') : null;
        if (old === text) { console.log('up to date: ' + path.relative(ROOT, out)); continue; }
        if (check) { console.error('STALE: ' + path.relative(ROOT, out) + ' (run node Tools/gen_params.js)'); stale++; continue; }
        fs.writeFileSync(out, text);
        console.log('wrote ' + path.relative(ROOT, out));
    }
    process.exit(stale ? 1 : 0);
}

if (require.main === module) main();
module.exports = { FIELDS, generate };
