using UnityEngine;

namespace AIHWSim.BodyEd
{
    /// <summary>
    /// Everything needed to rebuild a customised body, and nothing that can be
    /// derived from it.
    ///
    /// <b>What is deliberately NOT in here: the mesh.</b> A layout names the base
    /// body, four morph weights and the handful of vertices somebody actually
    /// pulled. The morph targets themselves are regenerated by
    /// <see cref="BodyMorphs"/> from the base mesh at load, deterministically, so
    /// storing them would be storing a function of data already present — and a
    /// stale copy of it the first time a body FBX is re-exported. That is what
    /// keeps a heavily customised car down to a few kilobytes of readable JSON
    /// instead of a megabyte of float triples.
    ///
    /// <b>Sparse offsets.</b> A sculpt stroke touches a neighbourhood of a shell
    /// that has thousands of vertices; a dense array would serialise the
    /// overwhelming majority as zeroes. Two parallel arrays rather than a list of
    /// pairs because <c>JsonUtility</c> cannot serialise a tuple without a wrapper
    /// type anyway, and because two flat arrays diff more legibly.
    ///
    /// <b>Sentinels follow the house convention</b> (see <c>VehicleDesign</c>): an
    /// absent JSON key leaves the field at its initialiser, and every initialiser
    /// here IS the do-nothing value. A file with only <c>carBasePrefabID</c> in it
    /// loads as an undeformed body rather than as an error.
    /// </summary>
    [System.Serializable]
    public class VehicleLayoutData
    {
        /// <summary>Schema version. Bump only for a change an older reader would
        /// misinterpret rather than merely ignore.</summary>
        public int version = 1;

        /// <summary>The catalogue body this was sculpted from —
        /// <c>BodyDef.id</c>, resolved through <c>BodyCatalog.ById</c>. Empty
        /// means "whatever is open", which is what makes a layout portable
        /// between shells at the caller's risk.</summary>
        public string carBasePrefabID = "";

        /// <summary>Axle-to-axle distance of the wheel markers, in metres. Not
        /// geometry — it is the context the body was shaped against, and it feeds
        /// the exposed-wheel term of the drag readout. 0 means "the editor's
        /// default", not "no wheelbase".</summary>
        public float wheelbaseLength;

        /// <summary>The design size the offsets were authored at, in metres. Kept
        /// so a future port can tell a layout sculpted on a stretched shell from
        /// one sculpted on a nominal shell.</summary>
        public Vector3 bodySize;

        /// <summary>Blendshape names, index-aligned with
        /// <see cref="blendShapeWeights"/>. Present so a load matches BY NAME:
        /// adding a fifth morph, or reordering the four, must not silently apply
        /// a roofline weight to a nose slider.</summary>
        public string[] blendShapeNames;

        /// <summary>Morph weights, 0..100, Unity's own scale.</summary>
        public float[] blendShapeWeights;

        /// <summary>Base-mesh vertex indices that were pulled. All members of a
        /// weld group appear, so a reload cannot half-move a seam.</summary>
        public int[] offsetIndex;

        /// <summary>Displacements in the mesh's AUTHOR units, index-aligned with
        /// <see cref="offsetIndex"/>. Author units rather than metres so a layout
        /// survives the body being resized.</summary>
        public Vector3[] offsetValue;

        /// <summary>Vertex count of the base mesh these indices refer to. A
        /// mismatch means the underlying FBX changed shape since the save, and the
        /// offsets are then meaningless rather than merely approximate — the
        /// loader drops them and says so.</summary>
        public int baseVertexCount;
    }
}
